{
	"id": "AVG-1000",
	"advisories": [
		{
			"id": "AVG-1000",
			"severity": [
				{
					"type": "vendor",
					"source": "security.archlinux.org",
					"vendor": "High"
				}
			],
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/AVG-1000"
				}
			]
		},
		{
			"id": "ASA-201907-2",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/ASA-201907-2"
				}
			]
		}
	],
	"vulnerabilities": [
		{
			"id": "CVE-2019-12781",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2019-12781"
				}
			]
		}
	],
	"detection": [
		{
			"ecosystem": "arch",
			"vulnerable": true,
			"package": {
				"name": "python-django"
			},
			"affected": {
				"type": "pacman",
				"range": [
					{
						"lt": "2.2.3-1"
					}
				],
				"fixed": [
					"2.2.3-1"
				]
			}
		}
	]
}
