{
	"id": "AVG-2038",
	"advisories": [
		{
			"id": "AVG-2038",
			"severity": [
				{
					"type": "vendor",
					"source": "security.archlinux.org",
					"vendor": "Medium"
				}
			],
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/AVG-2038"
				}
			]
		},
		{
			"id": "ASA-202106-25",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/ASA-202106-25"
				}
			]
		},
		{
			"id": "ASA-202106-25",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/ASA-202106-25"
				}
			]
		}
	],
	"vulnerabilities": [
		{
			"id": "CVE-2021-33503",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2021-33503"
				}
			]
		}
	],
	"detection": [
		{
			"ecosystem": "arch",
			"vulnerable": true,
			"package": {
				"name": "python-urllib3"
			},
			"affected": {
				"type": "pacman",
				"range": [
					{
						"lt": "1.26.5-1"
					}
				],
				"fixed": [
					"1.26.5-1"
				]
			}
		}
	]
}
