{
	"id": "AVG-1015",
	"advisories": [
		{
			"id": "ASA-201908-2",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/ASA-201908-2"
				}
			]
		},
		{
			"id": "AVG-1015",
			"severity": [
				{
					"type": "vendor",
					"source": "security.archlinux.org",
					"vendor": "Medium"
				}
			],
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/AVG-1015"
				}
			]
		}
	],
	"vulnerabilities": [
		{
			"id": "CVE-2019-14232",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2019-14232"
				}
			]
		},
		{
			"id": "CVE-2019-14233",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2019-14233"
				}
			]
		},
		{
			"id": "CVE-2019-14234",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2019-14234"
				}
			]
		},
		{
			"id": "CVE-2019-14235",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2019-14235"
				}
			]
		}
	],
	"detection": [
		{
			"ecosystem": "arch",
			"criteria": {
				"operator": "OR",
				"criterions": [
					{
						"vulnerable": true,
						"package": {
							"name": "python-django"
						},
						"affected": {
							"type": "pacman",
							"range": [
								{
									"lt": "2.2.4-1"
								}
							],
							"fixed": [
								"2.2.4-1"
							]
						}
					}
				]
			}
		}
	],
	"data_source": "arch"
}
