{
	"id": "AVG-1593",
	"advisories": [
		{
			"id": "ASA-202102-28",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/ASA-202102-28"
				}
			]
		},
		{
			"id": "AVG-1593",
			"severity": [
				{
					"type": "vendor",
					"source": "security.archlinux.org",
					"vendor": "Medium"
				}
			],
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/AVG-1593"
				}
			]
		}
	],
	"vulnerabilities": [
		{
			"id": "CVE-2021-23336",
			"references": [
				{
					"source": "security.archlinux.org",
					"url": "https://security.archlinux.org/CVE-2021-23336"
				}
			]
		}
	],
	"detection": [
		{
			"ecosystem": "arch",
			"criteria": {
				"operator": "OR",
				"criterions": [
					{
						"vulnerable": true,
						"package": {
							"name": "python-django"
						},
						"affected": {
							"type": "pacman",
							"range": [
								{
									"lt": "3.1.7-1"
								}
							],
							"fixed": [
								"3.1.7-1"
							]
						}
					}
				]
			}
		}
	]
}
